#!/bin/bash
# Copy and run this file from $HOME
#
# Get this by running:
#
#  git clone https://github.com/jcgregorio/home.git jcgregorio

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git ncurses-term screen ncurses-dev \
  mercurial python python-dev build-essential cmake

git config --global user.email "joe@bitworking.org"
git config --global user.name "Joe Gregorio"

mkdir ~/bin
mkdir ~/golib
mkdir --parents ~/.vim/tmp/backup
mkdir --parents ~/.vim/tmp/swap
ln -s /home/jcgregorio/jcgregorio/vim/vimrc ~/.vimrc
ln -s /home/jcgregorio/jcgregorio/bashrc ~/.bashrc

# Install go
cd ~
GOVER=go1.3.1.linux-amd64.tar.gz
wget https://storage.googleapis.com/golang/$GOVER
tar -xzf $GOVER

#Install latest vim
cd ~
mkdir src
cd src
hg clone https://vim.googlecode.com/hg/ vim
cd vim/src
./configure --with-features=huge --enable-pythoninterp --with-python-config-dir=/usr/lib/python2.7/config
make
sudo make install

mkdir -p ~/.vim/autoload ~/.vim/bundle; \
curl -Sso ~/.vim/autoload/pathogen.vim \
    https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

cd ~/.vim/bundle
git clone https://github.com/scrooloose/syntastic.git

cd ~/.vim/bundle
git clone https://github.com/SirVer/ultisnips.git

cd ~/.vim/bundle
git clone https://github.com/Valloric/YouCompleteMe.git
cd YouCompleteMe
./install.sh

# Test 256 colors
perl ~/jcgregorio/256colors2.pl
