#!/bin/bash
# Copy and run this file from $HOME
#
# Get this by running:
#
#  git clone https://github.com/jcgregorio/home.git jcgregorio

sudo apt update
sudo apt upgrade
sudo apt install git curl ncurses-term screen ncurses-dev \
  mercurial python python-dev build-essential cmake \
  bash-completion entr

git config --global user.email "joe@bitworking.org"
git config --global user.name "Joe Gregorio"

mkdir ~/bin
mkdir ~/golib
echo "source $HOME/jcgregorio/bashrc" >> ~/.bashrc
source ~/.bashrc

# Install go
cd ~

GOVER=go1.24.1.linux-amd64.tar.gz
wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
tar -xzf $GOVER

# Test 256 colors
perl ~/jcgregorio/256colors2.pl
