#!/bin/bash
# Copy and run this file from $HOME
#
# Get this by running:
#
#  git clone https://github.com/jcgregorio/home.git jcgregorio

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git ncurses-term screen ncurses-dev \
  mercurial python python-dev build-essential cmake \
  bash-completion

git config --global user.email "joe@bitworking.org"
git config --global user.name "Joe Gregorio"

mkdir ~/bin
mkdir ~/golib
mkdir --parents ~/.vim/tmp/backup
mkdir --parents ~/.vim/tmp/swap
rm ~/.vimrc
ln -s $HOME/jcgregorio/vim/vimrc ~/.vimrc
rm ~/.bashrc
ln -s $HOME/jcgregorio/bashrc ~/.bashrc
source ~/.bashrc

# Install go
cd ~
GOVER=go1.7.3.linux-amd64.tar.gz
wget https://storage.googleapis.com/golang/$GOVER
tar -xzf $GOVER

#Install latest vim
cd ~
mkdir src
cd src
git clone https://github.com/vim/vim.git
cd vim/src
./configure --with-features=huge --enable-pythoninterp --with-python-config-dir=/usr/lib/python2.7/config
make
sudo make install

mkdir -p ~/.vim/autoload ~/.vim/bundle && \
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

cd ~/.vim/bundle
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/SirVer/ultisnips.git
git clone https://github.com/honza/vim-snippets.git
git clone https://github.com/fatih/vim-go.git
git clone https://github.com/Valloric/YouCompleteMe.git
git clone https://github.com/othree/html5.vim
git clone git://github.com/tpope/vim-fugitive.git
cd YouCompleteMe
git submodule update --init --recursive
./install.sh

go get golang.org/x/tools/cmd/goimports

go get -u github.com/nsf/gocode
cd $GOPATH/src/github.com/nsf/gocode/vim
./update.sh


# Install depot_tools
cd
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

# Install cloud tools.
# curl https://sdk.cloud.google.com | bash

# Test 256 colors
perl ~/jcgregorio/256colors2.pl
