services:
  faster-whisper:
    image: fedirz/faster-whisper-server:latest-cuda
    container_name: jarvis-whisper
    ports:
      - "8000:8000"
    environment:
      - WHISPER__MODEL=base
      - WHISPER__DEVICE=cuda
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_KEEP_ALIVE=-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  piper:
    image: rhasspy/wyoming-piper:latest
    container_name: jarvis-piper
    ports:
      - "10200:10200"
    volumes:
      - piper_data:/data
    command: --voice en_US-hfc_male-medium
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

volumes:
  ollama_data:
  piper_data:
