#!/usr/bin/env bash
while true
do
  xsetroot -name "`hostname`   `date \"+%I:%M   %d %b %Y\"`               "
  sleep 20s
done &

gnome-settings-daemon &

trayer --expand true --widthtype request --edge bottom --align right &

nm-applet &
gnome-volume-control-applet &

sleep 15 && feh --bg-scale /usr/share/backgrounds/space-05.jpg &

export PATH=$PATH:$PATH/bin

# Log stderror to a file 
dwm 2> ~/.dwm.log
