#!/usr/bin/env bash
while true
do
  xsetroot -name "`hostname`   `date \"+%I:%M   %d %b %Y\"`  `acpi | sed 's#^[^,]*, ##' | sed 's#,.*##'`              "
  sleep 20s
done &

trayer --expand true --widthtype request --edge bottom --align right &

sleep 15 && feh --bg-scale /usr/share/backgrounds/Gwallpaper-Black-Goobuntu-default.png &
sleep 5 && xrandr --output DP-2 --auto --output DP-1 --auto --right-of DP-2 &

export PATH=$HOME/bin:$PATH

dmenu_path &

# Log stderror to a file 
dwm_remote 2> ~/.dwm_remote.log
